version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A music_app worker -l info
    volumes:
      - ./media:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - redis